name: Deploy Laravel Rumahweb Final

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploying...
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    # TAHAP 1: Deploy isi folder 'public' lokal ke 'public_html'
    - name: ðŸ“‚ Deploy Public Assets
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: ./ 
        exclude: |
          **/.git*
          **/.github*
          .ftp-deploy-sync-state.json

    # TAHAP 2: Deploy file inti ke folder 'laravel' (Keluar dari public_html)
    - name: ðŸ“‚ Deploy Core Laravel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ../laravel/
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          **/vendor/**
          **/public/**
          **/storage/**
          **/tests/**
          .env
          .ftp-deploy-sync-state.json